spring.application.name=StudentFeedBackSystem

server.port=8896
#data base properties
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.username=root
spring.datasource.password=Sai@30169
#hibernate properties
spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update

# ================= EMAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yadlapallipavansai@gmail.com
spring.mail.password=oiznvayvltplnswd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true